from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    DATASOURCE_NOT_FOUND = "DATASOURCE_NOT_FOUND"
    DATASOURCE_NOT_READY = "DATASOURCE_NOT_READY"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CSV_ENCODING_INVALID = "CSV_ENCODING_INVALID"
    CSV_HEADER_INVALID = "CSV_HEADER_INVALID"
    CSV_FORMAT_INVALID = "CSV_FORMAT_INVALID"
    SQLITE_INVALID = "SQLITE_INVALID"
    SQLITE_NO_USER_TABLES = "SQLITE_NO_USER_TABLES"
    DATASOURCE_CHECK_INTERRUPTED = "DATASOURCE_CHECK_INTERRUPTED"
    DATASOURCE_CHECK_FAILED = "DATASOURCE_CHECK_FAILED"
    DATALINK_UNAVAILABLE = "DATALINK_UNAVAILABLE"
    GRAPH_VERSION_NOT_FOUND = "GRAPH_VERSION_NOT_FOUND"
    DATASOURCE_MISMATCH = "DATASOURCE_MISMATCH"
    INVALID_QUERY = "INVALID_QUERY"
    DRAFT_STALE = "DRAFT_STALE"
    HEAD_STALE = "HEAD_STALE"
    REVISION_INVALID = "REVISION_INVALID"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PATH_OUTSIDE_ROOT = "PATH_OUTSIDE_ROOT"
    BUILD_ALREADY_RUNNING = "BUILD_ALREADY_RUNNING"
    BUILD_FAILED = "BUILD_FAILED"
    BUILD_INTERRUPTED = "BUILD_INTERRUPTED"
    MODEL_CONFIG_INVALID = "MODEL_CONFIG_INVALID"
    MODEL_PROFILE_NOT_FOUND = "MODEL_PROFILE_NOT_FOUND"
    MODEL_PROFILE_NOT_READY = "MODEL_PROFILE_NOT_READY"
    RUN_ALREADY_ACTIVE = "RUN_ALREADY_ACTIVE"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    RUN_ALREADY_FINISHED = "RUN_ALREADY_FINISHED"
    RUNTIME_START_FAILED = "RUNTIME_START_FAILED"
    RUN_TIMEOUT = "RUN_TIMEOUT"
    PROCESS_RESTARTED = "PROCESS_RESTARTED"
    VALIDATION_NOT_FOUND = "VALIDATION_NOT_FOUND"
    RELATION_NOT_FOUND = "RELATION_NOT_FOUND"
    RELATION_NOT_VALIDATABLE = "RELATION_NOT_VALIDATABLE"
    SCHEMA_TYPE_INCOMPATIBLE = "SCHEMA_TYPE_INCOMPATIBLE"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    SECURITY_POLICY_VIOLATION = "SECURITY_POLICY_VIOLATION"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AppError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        status_code: int = 400,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details or {}
